### ISSUE TITLE
Feature Request: support any type that implements Setter interface

### ISSUE THREAD

**Issue by skovtunenko** [BoRuDar/configuration#24]
Hello, thank you for a great library!

Sometimes there is a need to pass as ENV variable, not a single value, but a whole struct to override all the fields inside the struct at once. Most probably, this might be needed in highly configurable applications, where the number of exposed config params is big enough. 
To solve this issue in a generic way, the lib can give developers an ability to set a custom Unmarshaler/Setter for a type.

A typical interface to support this feature might look like this:
```go
type Setter interface {
	SetValue(string) error
}
```

Examples from other libs:
- https://github.com/kelseyhightower/envconfig#custom-decoders
- https://github.com/ilyakaznacheev/cleanenv#supported-types

**Comment by BoRuDar** [comment]
Feature is implemented in v4.2.0
