### ISSUE TITLE
Return errors

### ISSUE THREAD

**Issue by Davincible** [BoRuDar/configuration#30]
Hi, love your library. I just found out not all errors are returned, but instead handled by a func as here;

https://github.com/BoRuDar/configuration/blob/0bf51497fd0c0fc22938b4ac8f0d8e9aacd85cf9/configurator.go#L114

I found this quite strange behavior since the reset of the `InitValues` func does return errors. Would you be open to return all errors in `InitValues` directly?

I can make a PR

**Comment by BoRuDar** [comment]
Hi. Thank you for a request. The initial idea behind this was to fail only if **all** `Provider`s failed. But I can re-think the approach when I have some spare time (maybe even this weekend)

**Comment by BoRuDar** [comment]
Has been fixed in #32
