### ISSUE TITLE
Do not "log.Fatal" within the library

### ISSUE THREAD

**Issue by rusq** [BoRuDar/configuration#6]
Hey, @BoRuDar, that's a great library! I enjoy the lack of non-trivial third-party dependencies and the idea of having a `flags:` tag - that's really convenient

I may have a suggestion  - do you think that it would be better not to Fatal() on `InitValues()` from within the library, but return the error to the caller, so that they could decide what to do with it?

I know that you can set `failIfCannotSet` to `false`, it's just it seems that terminating the program from within library is a bit too much, because if you had something deferred this won't get executed, and it's always good to have the choice.  If it was, God forbid, `panic`, at least one could `recover`.

I take that you already got my point, but being courteous to other people that might be reading this, I will add an example:
```go
func main() {
	cfg := config.Config{}
	parser, err := configuration.New(
		&cfg,
		[]configuration.Provider{
			configuration.NewFlagProvider(&cfg),
			configuration.NewEnvProvider(),
		},
		false,
		true,
	)
	if err != nil {
		log.Fatal(err)
	}
	// The following line FATALs away
	parser.InitValues()
	// main logic ...
}
```

Proposed change:
```go
func main() {
	cfg := config.Config{}
	parser, err := configuration.New(
		&cfg,
		[]configuration.Provider{
			configuration.NewFlagProvider(&cfg),
			configuration.NewEnvProvider(),
		},
		false,
		true,
	)
	if err != nil {
		log.Fatal(err)
	}
	// After InitValues modified to return the value rather than die with shame
	if err := parser.InitValues(); err != nil {
		log.Println("oh shit, your configuration is borked, and that's why: %s", err)
		// close file descriptors
		// unwind winded things
		// terminate hostile elements
		log.Fatal("gg")
	}
	// main logic ...
}
```

**Comment by BoRuDar** [comment]
Hi @rusq 
Thank you for the feedback! 
At first implementations I used 'err' approach, then 'panic'. 
But I'm following 'fail fast' idea and that's why library stops execution. In my opinion correctness of a configuration is a corner stone of bug free applications, and that's why I force programs to stop in case of missing values (and also "zero" values). 
On the other hand the library still allows you to skip errors (for the convenience during development phase).  
Cheers,
Bogdan

**Comment by rusq** [comment]
Hey Bogdan!

Thanks for the quick reply. Well, I guess it's a matter of taste, and all tastes are different.

My preference is when library gives you a choice on how it dies (or not), for example [flag library][1].

I understand that implementing something like this would introduce breaking changes to existing implementations, and, of course I don't insist on anything, it's your call whether you want to have it in the code, but I see 2 non-breaking variants of changing, partly breaking variant and a breaking variant, if you don't mind I'll describe them for your consideration.

Non-breaking:
1. Add an `error` to `InitValues()` and when `failFast == false` - return the error instead of just leaving the structure unpopulated.
2. Add a new `InitValuesWithError()` method (name is questionable), that will return the error when `failFast == true`.  I dislike this variant as it adds another method - this adds complexity and code maintenance costs.

Partly breaking:
3. `panic()` instead of `log.Fatal`, with this, the library will still die, but the caller will be able to recover.  I think it's a bit dirty :)

Breaking:
4. Introducing something like [aforementioned flags flag] and having it instead of `failFast` bool in the constructor.

OR

5. EASY: leave everything as it is 😂

Again, I'm not insisting on changing anything - I just think it's nice to have something like this as an option.  The project I'm working on would benefit from that, but I'll survive without it of course.

Cheers,
Rustam

[1]: https://golang.org/pkg/flag/#ErrorHandling

**Comment by BoRuDar** [comment]
Hi Rustam!

Thank you for the ideas. I'll think about that. And I hope to hear some more opinions on this from others. At the moment I would like to keep current implementation.

Cheers,
Bogdan

**Comment by BoRuDar** [comment]
Hi Rustam!

I've redesigned error handling process and now you can change `log.Fatalf` behavior.

Cheers,
Bogdan

@rusq

**Comment by chabad360** [comment]
@BoRuDar I'd rather have `InitValues` log the error, than fail, as it's possible that the default for a configuration option is that it should be empty, perhaps there should be another provider that checks values, say `ValidationProvider`, that would simply validate each input, so if it's meant to be empty, it wont fail catastrophically.
